apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-injection
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: datainjection
            image: pawbis/datainjection:1.0
            args: ["/GCP/Volume", "data.json"]
            volumeMounts:
              - name: data-volume
                mountPath: "/GCP/Volume"
          volumes:
          - name: data-volume
            gcePersistentDisk:
              pdName: data-volume
              fsType: ext4
          restartPolicy: OnFailure