apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/pbisok/Documents/GCP"
