apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-gke-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: disk-volume